name: dart_ecpair
description: The ECPair module for dart_bitcoin
version: 1.0.1
homepage: https://github.com/dart-bitcoin-lib/dart-ecpair
repository: https://github.com/dart-bitcoin-lib/dart-ecpair
issue_tracker: https://github.com/dart-bitcoin-lib/dart-ecpair/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.1
  dart_bip32: ^2.0.1
  dart_wif: ^2.1.0
  pointycastle: ^3.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
